/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import Agregar.Jagregar;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import operaciones.operacionesTxt;
import operaciones.ventas;

/**
 *
 * @author Victor Rodriguez
 */
public class Jconsultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Jconsultas
     */
    DefaultTableModel mdltabla;
    Vector ca = new Vector();

    public Jconsultas() {
        initComponents();
        ca.addElement("Venta");
        ca.addElement("Empleado");
        ca.addElement("Fecha");
        ca.addElement("Talla");
        ca.addElement("Cantidad");
        ca.addElement("Codigo");
        ca.addElement("Modelo");
        ca.addElement("Color");
        ca.addElement("Precio");
        ca.addElement("Total");
        mdltabla = new DefaultTableModel(ca, 0);
        Jconsultas.tabla_ventas.setModel(mdltabla);
        mostrar();
        total();
    }
    operacionesTxt oper = new operacionesTxt();

    public void mostrar() {
        Jconsultas.tabla_ventas.setModel(oper.listaventas());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consulta1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        btnbuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labeltotal = new javax.swing.JLabel();
        txtconsulta1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscarfecha = new com.toedter.calendar.JDateChooser();
        btnfecha = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consultas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consulta:");

        consulta1.setBackground(new java.awt.Color(255, 255, 255));
        consulta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1486504352-checklist-clipboard-inventory-list-report-tasks-todo_81326.png"))); // NOI18N
        consulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1ActionPerformed(evt);
            }
        });

        tabla_ventas.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_ventas);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search_find_client_user_16693.png"))); // NOI18N
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("$");

        labeltotal.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        labeltotal.setForeground(new java.awt.Color(0, 0, 0));
        labeltotal.setText("jLabel2");

        txtconsulta1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtconsulta1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtconsulta1CaretUpdate(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha:");

        btnfecha.setText("Buscar por fecha");
        btnfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labeltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtconsulta1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(buscarfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbuscar)
                                .addGap(26, 26, 26)
                                .addComponent(consulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnfecha))
                        .addGap(296, 296, 296))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtconsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(buscarfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnfecha)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1ActionPerformed
        // TODO add your handling code here:
        mostrar();

    }//GEN-LAST:event_consulta1ActionPerformed
boolean si;

    public DefaultTableModel buscar(String nom) {
        String[] datos = new String[10];
        Vector ca = new Vector();
        ca.addElement("Venta");
        ca.addElement("Empleado");
        ca.addElement("Fecha");
        ca.addElement("Talla");
        ca.addElement("Cantidad");
        ca.addElement("Codigo");
        ca.addElement("Modelo");
        ca.addElement("Color");
        ca.addElement("Precio");
        ca.addElement("Total");
        DefaultTableModel tabla= new DefaultTableModel(ca,0);
        int filas = Jconsultas.tabla_ventas.getRowCount();
        for (int i = 0; i < filas; i++) {
            if (nom.equals(Jconsultas.tabla_ventas.getValueAt(i, 1).toString())) {
                si = true;
                datos[0] = Jconsultas.tabla_ventas.getValueAt(i, 0).toString();
                datos[1] = Jconsultas.tabla_ventas.getValueAt(i, 1).toString();
                datos[2] = Jconsultas.tabla_ventas.getValueAt(i, 2).toString();
                datos[3] = Jconsultas.tabla_ventas.getValueAt(i, 3).toString();
                datos[4] = Jconsultas.tabla_ventas.getValueAt(i, 4).toString();
                datos[5] = Jconsultas.tabla_ventas.getValueAt(i, 5).toString();
                datos[6] = Jconsultas.tabla_ventas.getValueAt(i, 6).toString();
                datos[7] = Jconsultas.tabla_ventas.getValueAt(i, 7).toString();
                datos[8] = Jconsultas.tabla_ventas.getValueAt(i, 8).toString();
                datos[9] = Jconsultas.tabla_ventas.getValueAt(i, 9).toString();
                tabla.addRow(datos);

            }else{
                this.mostrar();
            }

        }
        //this.tabla_ventas.setModel(modelo);
        return tabla;
    }
    public DefaultTableModel buscarporfecha(String fecha) {
        String[] datos = new String[10];
        Vector ca = new Vector();
        ca.addElement("Venta");
        ca.addElement("Empleado");
        ca.addElement("Fecha");
        ca.addElement("Talla");
        ca.addElement("Cantidad");
        ca.addElement("Codigo");
        ca.addElement("Modelo");
        ca.addElement("Color");
        ca.addElement("Precio");
        ca.addElement("Total");
        DefaultTableModel tabla= new DefaultTableModel(ca,0);
        int filas = Jconsultas.tabla_ventas.getRowCount();
        for (int i = 0; i < filas; i++) {
            if (fecha.equals(Jconsultas.tabla_ventas.getValueAt(i, 2).toString())) {
                si = true;
                datos[0] = Jconsultas.tabla_ventas.getValueAt(i, 0).toString();
                datos[1] = Jconsultas.tabla_ventas.getValueAt(i, 1).toString();
                datos[2] = Jconsultas.tabla_ventas.getValueAt(i, 2).toString();
                datos[3] = Jconsultas.tabla_ventas.getValueAt(i, 3).toString();
                datos[4] = Jconsultas.tabla_ventas.getValueAt(i, 4).toString();
                datos[5] = Jconsultas.tabla_ventas.getValueAt(i, 5).toString();
                datos[6] = Jconsultas.tabla_ventas.getValueAt(i, 6).toString();
                datos[7] = Jconsultas.tabla_ventas.getValueAt(i, 7).toString();
                datos[8] = Jconsultas.tabla_ventas.getValueAt(i, 8).toString();
                datos[9] = Jconsultas.tabla_ventas.getValueAt(i, 9).toString();
                tabla.addRow(datos);

            }else{
                this.mostrar();
            }

        }
        //this.tabla_ventas.setModel(modelo);
        return tabla;
    }
    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
//        if (si==true) {
//
            Jconsultas.tabla_ventas.setModel(buscar(txtconsulta1.getText()));
            txtconsulta1.setText("");
//        } else {
//            JOptionPane.showMessageDialog(null, "No existen datos", "ERROR", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtconsulta1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtconsulta1CaretUpdate
    
    }//GEN-LAST:event_txtconsulta1CaretUpdate

    private void btnfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfechaActionPerformed
        // TODO add your handling code here:
    /*
                DateFormat df = DateFormat.getDateInstance();
        String fecha = df.format(btn_fecha.getDate());
        */
    DateFormat df=DateFormat.getDateInstance();
    String fecha=df.format(this.buscarfecha.getDate());
                Jconsultas.tabla_ventas.setModel(buscarporfecha(fecha));
          //  txtconsulta1.setText("");
    
    }//GEN-LAST:event_btnfechaActionPerformed
    public void total() {
        int filas = Jconsultas.tabla_ventas.getRowCount();
        double totalE = 0.0;
        for (int i = 0; i < filas; i++) {
            totalE = totalE + Double.parseDouble(tabla_ventas.getValueAt(i, 9).toString());
        }
        labeltotal.setText(String.valueOf(totalE));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnfecha;
    private com.toedter.calendar.JDateChooser buscarfecha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton consulta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeltotal;
    public static javax.swing.JTable tabla_ventas;
    private javax.swing.JTextField txtconsulta1;
    // End of variables declaration//GEN-END:variables
}
