/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket;

import Agregar.Jagregar;
import Agregar.JagregarEmpleado;
//import Agregar.operacionesA;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import operaciones.ventas;
import operaciones.operacionesTxt;

/**
 *
 * @author Victor Rodriguez
 */
public class JticketEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form Jticket
     */
    public JticketEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    operacionesTxt objo = new operacionesTxt();
//    operacionesA objot = new operacionesA();
    ventas obje;
    public ArrayList<ventas> emp = new ArrayList();
    ventas[] ventas = new ventas[10];
    int cont=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        empleado = new javax.swing.JLabel();
        empleado1 = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        codigo1 = new javax.swing.JLabel();
        fechaO = new javax.swing.JLabel();
        fecha1 = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        codigo2 = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        fecha3 = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        codigo3 = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        fecha5 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        codigo4 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        fecha7 = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();
        fecha9 = new javax.swing.JLabel();
        recibido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        codigo5 = new javax.swing.JLabel();
        venta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ticket");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ZAPATERIA \"3 HERMANOS\" SA DE CV");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CALLE NIÑOS HEROES NUMERO 35");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("COL. SN FCO JAVIER, XOXOCOTLAN OAXACA, OAX.");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sucursal: 699 XOXO 5");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Empleado:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));

        empleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        empleado.setForeground(new java.awt.Color(0, 0, 0));
        empleado.setText("Empleado:");

        empleado1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        empleado1.setForeground(new java.awt.Color(0, 0, 0));
        empleado1.setText("Codigo:");

        codigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        codigo.setForeground(new java.awt.Color(0, 0, 0));
        codigo.setText("Codigo:");

        codigo1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        codigo1.setForeground(new java.awt.Color(0, 0, 0));
        codigo1.setText("Fecha: ");

        fechaO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fechaO.setForeground(new java.awt.Color(0, 0, 0));
        fechaO.setText("Fecha: ");

        fecha1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fecha1.setForeground(new java.awt.Color(0, 0, 0));
        fecha1.setText("Modelo:");

        modelo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        modelo.setForeground(new java.awt.Color(0, 0, 0));
        modelo.setText("Modelo:");

        codigo2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        codigo2.setForeground(new java.awt.Color(0, 0, 0));
        codigo2.setText("Talla:");

        numero.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        numero.setForeground(new java.awt.Color(0, 0, 0));
        numero.setText("Fecha: ");

        fecha3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fecha3.setForeground(new java.awt.Color(0, 0, 0));
        fecha3.setText("Color:");

        color.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        color.setForeground(new java.awt.Color(0, 0, 0));
        color.setText("Modelo:");

        codigo3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        codigo3.setForeground(new java.awt.Color(0, 0, 0));
        codigo3.setText("Cantidad:");

        cantidad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 0, 0));
        cantidad.setText("Fecha: ");

        fecha5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fecha5.setForeground(new java.awt.Color(0, 0, 0));
        fecha5.setText("Precio:");

        precio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setText("Modelo:");

        codigo4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        codigo4.setForeground(new java.awt.Color(0, 0, 0));
        codigo4.setText("Total:              $");

        total.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText("Fecha: ");

        fecha7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fecha7.setForeground(new java.awt.Color(0, 0, 0));
        fecha7.setText("Cambio:         $");

        cambio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cambio.setForeground(new java.awt.Color(0, 0, 0));
        cambio.setText("Modelo:");

        fecha9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fecha9.setForeground(new java.awt.Color(0, 0, 0));
        fecha9.setText("Recibido:       $");

        recibido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        recibido.setForeground(new java.awt.Color(0, 0, 0));
        recibido.setText("Modelo:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("********Gracias por su preferencia********");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/barcodehd_106060.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/workdone_87219.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelsymbol_80857.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        codigo5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        codigo5.setForeground(new java.awt.Color(0, 0, 0));
        codigo5.setText("Venta:");

        venta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        venta.setForeground(new java.awt.Color(0, 0, 0));
        venta.setText("Fecha: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo1)
                            .addComponent(codigo2)
                            .addComponent(codigo3)
                            .addComponent(codigo5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(venta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaO, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo4)
                            .addComponent(fecha9)
                            .addComponent(fecha7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recibido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(88, 88, 88)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(empleado)
                    .addComponent(empleado1)
                    .addComponent(codigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo1)
                    .addComponent(fechaO)
                    .addComponent(fecha1)
                    .addComponent(modelo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo2)
                    .addComponent(numero)
                    .addComponent(fecha3)
                    .addComponent(color))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo3)
                    .addComponent(cantidad)
                    .addComponent(fecha5)
                    .addComponent(precio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigo5)
                        .addComponent(venta))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigo4)
                        .addComponent(total)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha9)
                    .addComponent(recibido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha7)
                    .addComponent(cambio))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        obje = new ventas();
        obje.setVenta(Integer.parseInt(JticketEmpleado.venta.getText()));
        obje.setEmpleado(JticketEmpleado.empleado.getText());
        obje.setFecha(JticketEmpleado.fechaO.getText());
        obje.setTalla(Integer.parseInt(JticketEmpleado.numero.getText()));
        obje.setCantidad(Integer.parseInt(JticketEmpleado.cantidad.getText()));
        obje.setCodigo(Integer.parseInt(JticketEmpleado.codigo.getText()));
        obje.setModelo(JticketEmpleado.modelo.getText());
        obje.setColor(JticketEmpleado.color.getText());
        obje.setPrecio(Double.parseDouble(JticketEmpleado.precio.getText()));
        obje.setTotal(Double.parseDouble(JticketEmpleado.total.getText()));
        this.objo.Escritura("ventas.txt", this.obje);
        JticketEmpleado.empleado.setText("");
        JticketEmpleado.fechaO.setText("");
        JticketEmpleado.numero.setText("");
        JticketEmpleado.cantidad.setText("");
        JticketEmpleado.codigo.setText("");
        JticketEmpleado.modelo.setText("");
        JticketEmpleado.color.setText("");
        JticketEmpleado.precio.setText("");
        JticketEmpleado.total.setText("");
        JticketEmpleado.venta.setText("");
        JticketEmpleado.recibido.setText("");
        JticketEmpleado.cambio.setText("");
//        Jagregar.cboempleado.setSelectedIndex(0);
//    Jagregar.btn_fecha.setDateFormatString("");
        JagregarEmpleado.txtnum_empleado.setText("");
        JagregarEmpleado.txtcantidad_empleado.setText("");
        JagregarEmpleado.txtcodigo_empleado.setText("");
        JagregarEmpleado.txtmodelo_modelo.setText("");
        JagregarEmpleado.txtcolor_empleado.setText("");
        JagregarEmpleado.txtprecio_empleado.setText("");
        JagregarEmpleado.txttotal_empleado.setText("");
        JagregarEmpleado.txtcambio_empleado.setText("");
        JagregarEmpleado.txtrecibido_empleado.setText("");
        JagregarEmpleado.txtventa_empleado.setText("");
//        Jagregar a = new Jagregar();
//      //  a.setVisible(rootPaneCheckingEnabled);
//        a.setVisible(rootPaneCheckingEnabled);
//        a.numeroVentas();
//        Jagregar a = new Jagregar();
//        int pos=a.getF();
//        String s=Jagregar.tablaproductos.getValueAt(pos, 5).toString();
//        int stock=;
//        this.objot.restarInv(Integer.parseInt(Jagregar.txtcantidad.getText()), stock);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JticketEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JticketEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JticketEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JticketEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JticketEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel cambio;
    public static javax.swing.JLabel cantidad;
    public static javax.swing.JLabel codigo;
    private javax.swing.JLabel codigo1;
    private javax.swing.JLabel codigo2;
    private javax.swing.JLabel codigo3;
    private javax.swing.JLabel codigo4;
    private javax.swing.JLabel codigo5;
    public static javax.swing.JLabel color;
    public static javax.swing.JLabel empleado;
    private javax.swing.JLabel empleado1;
    private javax.swing.JLabel fecha1;
    private javax.swing.JLabel fecha3;
    private javax.swing.JLabel fecha5;
    private javax.swing.JLabel fecha7;
    private javax.swing.JLabel fecha9;
    public static javax.swing.JLabel fechaO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel modelo;
    public static javax.swing.JLabel numero;
    public static javax.swing.JLabel precio;
    public static javax.swing.JLabel recibido;
    public static javax.swing.JLabel total;
    public static javax.swing.JLabel venta;
    // End of variables declaration//GEN-END:variables
}
